### ISSUE TITLE
Best practices for public path

### ISSUE THREAD

**Issue by brresnic** [jeffreylanters/react-unity-webgl#12]
This repo is awesome, and the documentation is great!

I would appreciate it if the documentation included a paragraph on best practices for making src and loader files available on a public path. I know this may vary from application to application, but I think addressing the topic would be helpful for many non-expert react users who want to integrate Unity into their application.

**Comment by jeffreylanters** [comment]
Hi! Thanks, and I did make some changes to the readme for making it clear your build should be public. But the problem is indeed that this can vary from app to app. The idea is that you place your build in a folder which is public to a web server by adress. The `src` and `loader` props have a path that is **relative to your html file** . Let me know if this works for you!
