### ISSUE TITLE
Unity to react communication wiki

### ISSUE THREAD

**Issue by zmays** [jeffreylanters/react-unity-webgl#128]
I'd make a pr, but not sure how you want to handle that for the wiki. Just a quick suggestion for this code snippet here:

```
using UnityEngine;
using System.Runtime.InteropServices;

public class GameController : MonoBehaviour {

  // Import the JSLib as following. Make sure the
  // names match with the JSLib file we've just created.

  [DllImport("__Internal")]
  private static extern void GameOver (int score);

  // Then create a function that is going to trigger
  // the imported function from our JSLib.

  public void GameOver (int score) {
    GameOver (score);
  }
}
```

this may be less confusing for people testing it out the first time:

```
using UnityEngine;
using System.Runtime.InteropServices;

public class GameController : MonoBehaviour {

  // Import the JSLib as following. Make sure the
  // names match with the JSLib file we've just created.

  [DllImport("__Internal")]
  private static extern void GameOver (int score);

  // Example test call of function onEnable
  private void OnEnable() {
    // prevent calling when not running in webGl env, e.g editor
    if (Application.platform == RuntimePlatform.WebGLPlayer) {
      int sampleInt = 1
      GameOver(sampleInt)
    }
  }
}

```

**Comment by keithweaver** [comment]
Thanks @zmays for providing this example. I was getting stuck here with the two following errors since I assumed the naming needed to match. First one because I was importing `GameOver` and declaring `GameOver` in the same namespace. I just assumed they needed to match (I was wrong).

![Screen Shot 2021-02-03 at 7 00 19 AM](https://user-images.githubusercontent.com/6508608/106746221-3a52e680-65f0-11eb-99e5-5ae1f91b4c17.png)

This second one was because I was trying to build it outside of WebGL. 

![Screen Shot 2021-02-03 at 7 04 30 AM](https://user-images.githubusercontent.com/6508608/106746217-39ba5000-65f0-11eb-92a9-a8205bc978ea.png)

By adding, `if (Application.platform == RuntimePlatform.WebGLPlayer) {`, solved my problem.

**Comment by jeffreylanters** [comment]
Completely missed this issue, good suggestion. I'll edit the Wiki!
