### ISSUE TITLE
Change Resolution

### ISSUE THREAD

**Issue by nipundavid** [jeffreylanters/react-unity-webgl#133]
Hi,

I am not able to change the window size as mentioned in the documentation

`<Unity unityContext={unityContext} height="100%" width="950px" />`

I tried changing the values to percentage pixels my layout is still kinda landscape

like this
`<Unity unityContent={unityContent} height="730px" width="480px" />`
![Capture](https://user-images.githubusercontent.com/2108309/99911753-7d552b80-2d1c-11eb-9cfd-fe5520bfc86c.PNG)

here are Unity3D settings
![Capture](https://user-images.githubusercontent.com/2108309/99911766-94941900-2d1c-11eb-81f6-00bcad627890.PNG)

here is when I run the build as standalone on browser
![Capture](https://user-images.githubusercontent.com/2108309/99911804-c7d6a800-2d1c-11eb-98d6-ab2237971d9f.PNG)

as you can see it is running in the desired resolution 

Am I missing something?

regards,
Nipun Davod

**Comment by jeffreylanters** [comment]
Hi! Thanks for opening an issue. 

There is a little bit of misunderstanding about the WebGL width and height properties in Unity. As you can see below these options, you can choose a template which Unity will use when building your application. Some template provide some variables which Unity detects and allows the developer to enter from the enter. Height and width are such values, these do not change anything about your build, except they alter the HTML files that comes with your build and sets the height and width value. (TL;D'R Width and Height in Unity don't do anything, no need to use).

You can use percentages in as the Height and Width properties inside of React and then go with regular responsive styling in order to scale your application.

**Comment by nipundavid** [comment]
hi @jeffreylanters , so I am not able to follow you completely. I also tried the height and width in %age but they didn't change the resolution the view. Can you please share the exact steps or documentation which I can refer to?

regards,
Nipun David

**Comment by Slympp** [comment]
Hi @nipundavid , I encountered the same issue with the 7.x version and the width/height props having no effects. My solution was to override the style with the !important rule, for example :

```typescript
<Unity unityContent={this.unityContent} className="unity-content"/>
```

```css
// CSS
.unity-content {
    height: 640px !important;
    width: 480px !important;
}
```

---

In my case, the main problem was actually what seemed like a fixed 2:1 aspect ratio (i.e. the height of the canvas being always equals to 50% of its width), so I'll let my *somehow responsive* solution here if anyone needs it.

```typescript
componentDidMount() {
    window.addEventListener('resize', this.resize);

    this.resize();
}

componentWillUnmount() {
    window.removeEventListener('resize', this.resize);
}

resize = () => {
    const unityElement = document.getElementById("unity") as HTMLInputElement;
    const width = parseFloat(window.getComputedStyle(unityElement).width);

    unityElement.setAttribute("style", "height: " + (width / 16 * 9) + "px !important");
}

render() {
    return (
        <div id="unity">
            <Unity unityContent={this.unityContent} />
        </div>
    );
}
```

**Comment by zmays** [comment]
I had luck with this:

In my case I have a header which is why I'm subtracting 64px

```
      <div style={{ height: 'calc(100vh - 64px)', width: '100vw', margin: '0px', padding: '0px', border: '0px' }}>
        <Unity height='100%' width='100%' unityContext={context} />
      </div>
```
