### ISSUE TITLE
Documentation for Unity to React communication

### ISSUE THREAD

**Issue by l0wrenz** [jeffreylanters/react-unity-webgl#258]
While trying to implement Unity to React communication, I followed your directions in the readme:
```js
// File: MyPlugin.jslib

mergeInto(LibraryManager.library, {
  GameOver: function (userName, score) {
    dispatchReactUnityEvent("GameOver", Pointer_stringify(userName), score);
  },
});
```

I got an undefined function error and changed it to:

```js
// File: MyPlugin.jslib

mergeInto(LibraryManager.library, {
  GameOver: function (userName, score) {
    window.dispatchReactUnityEvent("GameOver", Pointer_stringify(userName), score);
  },
});
```

Now it works. Maybe I just did something wrong while setting the project up.

**Comment by jeffreylanters** [comment]
Hi! Thanks for your suggestion. It should work in both cases. The dispatch method is actually attached to the window, and since the window is also global the code snippet above _should_ work as well. But nonetheless I think it would be a good addition. If you'd like to, please feel free to open a PR containing this documentation change.
