### ISSUE TITLE
Load UnityContent in a webworker

### ISSUE THREAD

**Issue by JigneshVasoya3292** [jeffreylanters/react-unity-webgl#80]
**Describe the bug**
It's not a bug but more of a query. Is there a way I can load UnityContent in a webworker on my frontend?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jeffreylanters** [comment]
Hi! I've never worked with WebWorkers. I'm not sure if it is possible, especially since Unity Builds can get quite large quickly. -- I will leaved this issue open for anyone who might be able to help you. If you're going to continue your search, I don't think it's necessary to search in the context of this module, you can search for Unity WebGL in general. If you find something interesting, feel free to let me know right here!
